"use client";

import { useEffect, useState } from "react";

const nav=[["▦","Tableau de bord"],["✦","Agent SEO"],["▤","Pages & Articles"],["▣","Calendrier éditorial"],["✎","Audit On-page"],["?","Schema"],["⌕","Mots-clés"],["♟","Concurrents"],["↗","Backlinks"],["⌖","SEO local"],["◎","Google Data"],["⚙","Paramètres"]];
const actions=[["Priorité haute","Analyser les cannibalisations","Plusieurs intentions présentent des chevauchements entre URL.","danger"],["Opportunité","Punaises de lit Toulon","La page est proche du Top 10 : enrichir le contenu local et le maillage.","warn"],["Technique","Schema LocalBusiness","Préparer les données structurées de l'entreprise.","info"]];

type WpItem={id:number;slug:string;status:string;link:string;title:{rendered?:string;raw?:string};modified:string};
type WpData={ok:boolean;site?:string;user?:{name:string};counts?:{pagesReturned:number;postsReturned:number};pages?:WpItem[];posts?:WpItem[];error?:string};
type GRow={keys:string[];clicks:number;impressions:number;ctr:number;position:number};
type Cannibal={cluster:string;queries:string[];severity:string;score:number;reason:string;pages:{url:string;clicks:number;impressions:number;position:number;share:number}[];pageCount:number;clicks:number;impressions:number};
type GData={ok:boolean;period?:{startDate:string;endDate:string;days:number};totals?:{clicks:number;impressions:number;ctr:number;position:number};queries?:GRow[];pages?:GRow[];cannibalization?:Cannibal[];error?:string};

export default function Home(){
 const [active,setActive]=useState("Tableau de bord");
 const [wp,setWp]=useState<WpData|null>(null);
 const [gsc,setGsc]=useState(false); const [gd,setGd]=useState<GData|null>(null);
 useEffect(()=>{fetch("/api/wordpress").then(r=>r.json()).then(setWp).catch(()=>setWp({ok:false,error:"Connexion impossible"})); fetch("/api/google/status").then(r=>r.json()).then(d=>{setGsc(!!d.connected);if(d.connected)fetch("/api/google/search-console").then(r=>r.json()).then(setGd).catch(()=>{})}).catch(()=>{})},[]);
 return <main><aside><div className="brand"><div className="shield">RN</div><div><b>Riviera Nuisibles</b><small>SEO COCKPIT</small></div></div><p className="section">PILOTAGE</p>{nav.map((n)=><button className={"nav "+(active===n[1]?"active":"")} key={n[1]} onClick={()=>setActive(n[1])}><span>{n[0]}</span>{n[1]}{n[1]==="Agent SEO"&&<em>3</em>}</button>)}</aside><section className="content">{active==="Pages & Articles"?<Content wp={wp}/>:active==="Google Data"?<GoogleData data={gd}/>:active==="Mots-clés"?<Keywords data={gd}/>:active==="Agent SEO"?<AgentSEO data={gd}/>:<Dashboard wp={wp} gsc={gsc} gd={gd}/>}</section></main>
}
function Dashboard({wp,gsc,gd}:{wp:WpData|null,gsc:boolean,gd:GData|null}){return <><header><div><p className="eyebrow">RIVIERA NUISIBLES · rivieranuisibles.fr</p><h1>Bonjour 👋</h1><p className="sub">Voici ce qui mérite votre attention aujourd'hui.</p></div><button>+ Nouvelle analyse</button></header><div className="stats"><Card k="Score SEO" v="—" s="Calculé avec les vraies données"/><Card k="Clics Google · 28 j" v={gd?.ok?String(Math.round(gd.totals?.clicks||0)):"—"} s={gd?.ok?`${Math.round(gd.totals?.impressions||0).toLocaleString("fr-FR")} impressions`:"Chargement Search Console..."}/><Card k="Contenus WordPress" v={wp?.ok?String((wp.pages?.length||0)+(wp.posts?.length||0)):"—"} s={wp?.ok?"Synchronisation active":"Connexion en cours..."}/><Card k="Actions prioritaires" v="3" s="À examiner aujourd'hui"/></div><div className="grid"><div className="panel wide"><div className="panelHead"><div><span className="dot"></span><b>Agent SEO</b><p>Recommandations classées par impact</p></div><button className="ghost">Tout analyser</button></div>{actions.map(a=><div className="action" key={a[1]}><span className={"badge "+a[3]}>{a[0]}</span><div><b>{a[1]}</b><p>{a[2]}</p></div><button className="arrow">→</button></div>)}</div><div className="panel"><div className="panelHead"><div><b>État des connexions</b><p>Sources de données</p></div></div><Connection name="WordPress" state={wp?.ok?"Connecté":"Connexion..." } ok={!!wp?.ok}/><Connection name="Search Console" state={gsc?"Connecté":"À connecter"} ok={gsc}/><Connection name="Google Analytics 4" state="À connecter"/><Connection name="API SEO" state="À connecter"/><button className="full" onClick={()=>{if(!gsc) location.href="/api/google/login"}}>{gsc?"Search Console connecté":"Connecter Search Console"}</button></div></div><div className="panel roadmap"><div className="panelHead"><div><b>Vue d'ensemble</b><p>Le cockpit part volontairement de données réelles, jamais de chiffres simulés.</p></div></div><div className="empty"><div>⌁</div><h2>{wp?.ok?"WordPress est connecté":"Connexion WordPress en cours"}</h2><p>{wp?.ok?"Les contenus du site sont maintenant synchronisés. Ouvrez « Pages & Articles » pour les consulter.":"Les données apparaîtront dès que la connexion sera disponible."}</p></div></div></>}

function Content({wp}:{wp:WpData|null}){
 const [kind,setKind]=useState<"pages"|"posts">("pages");
 const items=kind==="pages"?(wp?.pages||[]):(wp?.posts||[]);
 return <><header><div><p className="eyebrow">CONTENU WORDPRESS</p><h1>Pages & Articles</h1><p className="sub">Contenus récupérés directement depuis rivieranuisibles.fr.</p></div><button onClick={()=>location.reload()}>↻ Actualiser</button></header>
 <div className="stats"><Card k="Connexion" v={wp?.ok?"Active":"—"} s={wp?.ok?"WordPress synchronisé":"Vérification..."}/><Card k="Pages chargées" v={wp?.ok?String(wp.pages?.length||0):"—"} s="Derniers contenus récupérés"/><Card k="Articles chargés" v={wp?.ok?String(wp.posts?.length||0):"—"} s="Derniers contenus récupérés"/><Card k="Compte" v={wp?.user?.name||"—"} s="Utilisateur WordPress"/></div>
 <div className="panel contentPanel"><div className="contentToolbar"><div><b>Contenus du site</b><p>Données réelles de l'API WordPress</p></div><div className="tabs"><button className={kind==="pages"?"tab activeTab":"tab"} onClick={()=>setKind("pages")}>Pages</button><button className={kind==="posts"?"tab activeTab":"tab"} onClick={()=>setKind("posts")}>Articles</button></div></div>
 {!wp?<div className="loading">Chargement de WordPress…</div>:!wp.ok?<div className="errorBox">Connexion WordPress impossible : {wp.error}</div>:<div className="contentTable"><div className="tableRow tableHead"><span>Titre</span><span>Statut</span><span>Dernière modification</span><span></span></div>{items.map(item=><div className="tableRow" key={item.id}><div><b dangerouslySetInnerHTML={{__html:item.title.rendered||item.title.raw||item.slug}}/><small>/{item.slug}</small></div><span className={"state "+item.status}>{item.status==="publish"?"Publié":item.status}</span><span>{new Date(item.modified).toLocaleDateString("fr-FR")}</span><a href={item.link} target="_blank" rel="noreferrer">Voir ↗</a></div>)}</div>}</div></>
}
function Card({k,v,s}:{k:string,v:string,s:string}){return <div className="card"><p>{k}</p><strong>{v}</strong><small>{s}</small></div>}
function Connection({name,state,ok=false}:{name:string,state:string,ok?:boolean}){return <div className="connection"><span className={"status "+(ok?"connected":"")}></span><b>{name}</b><small className={ok?"okText":""}>{state}</small></div>}

function GoogleData({data}:{data:GData|null}){
 if(!data)return <><header><div><p className="eyebrow">GOOGLE SEARCH CONSOLE</p><h1>Google Data</h1><p className="sub">Chargement des données réelles…</p></div></header></>;
 if(!data.ok)return <><header><div><p className="eyebrow">GOOGLE SEARCH CONSOLE</p><h1>Google Data</h1><p className="sub">{data.error||"Données indisponibles"}</p></div></header></>;
 const t=data.totals!;
 return <><header><div><p className="eyebrow">GOOGLE SEARCH CONSOLE · {data.period?.days} JOURS</p><h1>Google Data</h1><p className="sub">Performances organiques réelles de rivieranuisibles.fr.</p></div><button onClick={()=>location.reload()}>↻ Actualiser</button></header>
 <div className="stats"><Card k="Clics" v={Math.round(t.clicks).toLocaleString("fr-FR")} s="Depuis Google"/><Card k="Impressions" v={Math.round(t.impressions).toLocaleString("fr-FR")} s="Visibilité Google"/><Card k="CTR moyen" v={(t.ctr*100).toFixed(2)+" %"} s="Clics ÷ impressions"/><Card k="Position moyenne" v={t.position.toFixed(1)} s="Toutes requêtes"/></div>
 <DataTable title="Requêtes Google" rows={data.queries||[]} label="Mot-clé"/><DataTable title="Pages dans Google" rows={data.pages||[]} label="URL"/>
 <div className="panel contentPanel"><div className="contentToolbar"><div><b>Cannibalisation SEO à examiner</b><p>Les faux positifs faibles sont filtrés. Le niveau indique la force du signal, pas une consigne de suppression.</p></div></div><div className="contentTable"><div className="tableRow tableHead"><span>Requête / diagnostic</span><span>Niveau</span><span>Impressions</span><span>Pages</span></div>{(data.cannibalization||[]).slice(0,30).map(x=><div className="tableRow" key={x.cluster}><div><b>{x.cluster}</b><small>{x.reason}</small><small>{x.queries.slice(0,4).join(" · ")}</small><small>{x.pages.slice(0,3).map(p=>new URL(p.url).pathname+" ("+Math.round(p.share*100)+" %, pos. "+p.position.toFixed(1)+")").join(" · ")}</small></div><span className={"state "+(x.severity==="Élevée"?"draft":"publish")}>{x.severity}</span><span>{Math.round(x.impressions)}</span><span>{x.pageCount}</span></div>)}</div></div></>
}
function Keywords({data}:{data:GData|null}){return <><header><div><p className="eyebrow">SEARCH CONSOLE</p><h1>Mots-clés</h1><p className="sub">Les requêtes qui affichent réellement Riviera Nuisibles dans Google.</p></div></header>{data?.ok?<DataTable title="Mots-clés organiques" rows={data.queries||[]} label="Requête"/>:<div className="panel"><p>Chargement des données Search Console…</p></div>}</>}
function DataTable({title,rows,label}:{title:string,rows:GRow[],label:string}){return <div className="panel contentPanel"><div className="contentToolbar"><div><b>{title}</b><p>Données Search Console</p></div></div><div className="contentTable"><div className="tableRow tableHead"><span>{label}</span><span>Clics</span><span>Impressions</span><span>Position</span></div>{rows.slice(0,50).map((r,i)=><div className="tableRow" key={(r.keys?.[0]||"")+i}><div><b>{label==="URL"?(new URL(r.keys[0])).pathname:r.keys[0]}</b></div><span>{Math.round(r.clicks)}</span><span>{Math.round(r.impressions)}</span><span>{r.position.toFixed(1)}</span></div>)}</div></div>}

function AgentSEO({data}:{data:GData|null}){
 const [selected,setSelected]=useState<Cannibal|null>(null); const [wpAnalysis,setWpAnalysis]=useState<any>(null); const [loading,setLoading]=useState(false); const cases=data?.cannibalization||[];
 const analyze=async(x:Cannibal)=>{if(selected?.cluster===x.cluster){setSelected(null);setWpAnalysis(null);return}setSelected(x);setWpAnalysis(null);setLoading(true);try{const q=x.pages.slice(0,4).map(p=>"analyze="+encodeURIComponent(p.url)).join("&");const r=await fetch("/api/wordpress?"+q);setWpAnalysis(await r.json())}catch{setWpAnalysis({ok:false,error:"Analyse WordPress impossible"})}finally{setLoading(false)}};
 return <><header><div><p className="eyebrow">AGENT SEO · MODE APPROBATION</p><h1>Agent SEO</h1><p className="sub">Analyse les signaux réels avant toute modification de WordPress.</p></div></header>
 <div className="stats"><Card k="Cas détectés" v={data?.ok?String(cases.length):"—"} s="Cannibalisations qualifiées"/><Card k="Priorité élevée" v={data?.ok?String(cases.filter(x=>x.severity==="Élevée").length):"—"} s="À examiner en premier"/><Card k="Source" v="GSC" s="Données Search Console"/><Card k="Mode" v="Manuel" s="Aucune modification automatique"/></div>
 <div className="panel contentPanel"><div className="contentToolbar"><div><b>File d'analyse</b><p>Cliquez sur Analyser pour déplier le diagnostic directement sous le cas.</p></div></div>
 <div className="contentTable"><div className="tableRow tableHead"><span>Cluster</span><span>Niveau</span><span>Impressions</span><span></span></div>
 {cases.slice(0,20).map(x=><div key={x.cluster}><div className="tableRow"><div><b>{x.cluster}</b><small>{x.queries.length} requête(s) · {x.pageCount} pages concernées</small></div><span className={"state "+(x.severity==="Élevée"?"draft":"publish")}>{x.severity}</span><span>{Math.round(x.impressions)}</span><button className="ghost" onClick={()=>analyze(x)}>{selected?.cluster===x.cluster?"Refermer ↑":"Analyser ↓"}</button></div>
 {selected?.cluster===x.cluster&&<div style={{padding:"18px 22px",borderTop:"1px solid #e7ece9",background:"#f8fbf9"}}><div className="action"><span className="badge danger">Signal {x.severity}</span><div><b>{x.pages.length} pages se chevauchent</b><p>{x.reason}</p><small>{x.queries.slice(0,6).join(" · ")}</small></div></div>{x.pages.slice(0,4).map(p=><div className="action" key={p.url}><span className="badge info">{Math.round(p.share*100)} %</span><div><b>{new URL(p.url).pathname}</b><p>{Math.round(p.impressions)} impressions · position {p.position.toFixed(1)} · {Math.round(p.clicks)} clic(s)</p></div><a href={p.url} target="_blank" rel="noreferrer">Voir ↗</a></div>)}<div className="empty"><h2>Analyse du contenu WordPress</h2>{loading?<p>Lecture des pages en cours…</p>:wpAnalysis?.ok?<div>{wpAnalysis.pages.map((p:any)=><div className="action" key={p.url}><span className="badge info">{p.found?p.words+" mots":"Introuvable"}</span><div><b>{p.title||p.slug}</b><p>{p.found?(p.type==="pages"?"Page WordPress":"Article WordPress")+" · modifié le "+new Date(p.modified).toLocaleDateString("fr-FR"):"Contenu non retrouvé dans WordPress"}</p></div></div>)}{wpAnalysis.comparison&&<div><div className="action"><span className="badge info">{wpAnalysis.comparison.overlap}%</span><div><b>Chevauchement lexical estimé</b><p>{wpAnalysis.comparison.intent}</p></div></div><div className="action"><span className="badge publish">Proposition</span><div><b>Action recommandée avant validation</b><p>{wpAnalysis.comparison.recommendation}</p><small>Termes communs : {wpAnalysis.comparison.sharedTerms?.slice(0,10).join(" · ")}</small></div></div><div style={{marginTop:18}}><b>Plan de correction proposé</b>{wpAnalysis.comparison.plan?.map((step:any,i:number)=><div className="action" key={i}><span className="badge info">{i+1}</span><div><b>{step.label} · {step.action}</b><p>{step.details}</p><small>{new URL(step.target).pathname}</small></div></div>)}</div><p><b>Aucune modification n'a été appliquée à WordPress.</b> Le plan doit être approuvé avant toute écriture.</p></div>}</div>:<p>{wpAnalysis?.error||"Préparation de l'analyse…"}</p>}</div></div>}</div>)}</div></div></>
}
