"use client";

import { useEffect, useState } from "react";

const nav=[["▦","Tableau de bord"],["✦","Agent SEO"],["▤","Pages & Articles"],["▣","Calendrier éditorial"],["✎","Audit On-page"],["?","Schema"],["⌕","Mots-clés"],["♟","Concurrents"],["↗","Backlinks"],["⌖","SEO local"],["◎","Google Data"],["⚙","Paramètres"]];
const actions=[["Priorité haute","Connecter Google Search Console","Récupérer les clics, impressions, CTR et positions réelles.","danger"],["Opportunité","Punaises de lit Toulon","La page est proche du Top 10 : enrichir le contenu local et le maillage.","warn"],["Technique","Schema LocalBusiness","Préparer les données structurées de l'entreprise.","info"]];

type WpItem={id:number;slug:string;status:string;link:string;title:{rendered?:string;raw?:string};modified:string};
type WpData={ok:boolean;site?:string;user?:{name:string};counts?:{pagesReturned:number;postsReturned:number};pages?:WpItem[];posts?:WpItem[];error?:string};

export default function Home(){
 const [active,setActive]=useState("Tableau de bord");
 const [wp,setWp]=useState<WpData|null>(null);
 useEffect(()=>{fetch("/api/wordpress").then(r=>r.json()).then(setWp).catch(()=>setWp({ok:false,error:"Connexion impossible"}))},[]);
 return <main><aside><div className="brand"><div className="shield">RN</div><div><b>Riviera Nuisibles</b><small>SEO COCKPIT</small></div></div><p className="section">PILOTAGE</p>{nav.map((n)=><button className={"nav "+(active===n[1]?"active":"")} key={n[1]} onClick={()=>setActive(n[1])}><span>{n[0]}</span>{n[1]}{n[1]==="Agent SEO"&&<em>3</em>}</button>)}</aside><section className="content">{active==="Pages & Articles"?<Content wp={wp}/>:<Dashboard wp={wp}/>}</section></main>
}
function Dashboard({wp}:{wp:WpData|null}){return <><header><div><p className="eyebrow">RIVIERA NUISIBLES · rivieranuisibles.fr</p><h1>Bonjour 👋</h1><p className="sub">Voici ce qui mérite votre attention aujourd'hui.</p></div><button>+ Nouvelle analyse</button></header><div className="stats"><Card k="Score SEO" v="—" s="Calculé avec les vraies données"/><Card k="Clics Google · 28 j" v="—" s="Search Console à connecter"/><Card k="Contenus WordPress" v={wp?.ok?String((wp.pages?.length||0)+(wp.posts?.length||0)):"—"} s={wp?.ok?"Synchronisation active":"Connexion en cours..."}/><Card k="Actions prioritaires" v="3" s="À examiner aujourd'hui"/></div><div className="grid"><div className="panel wide"><div className="panelHead"><div><span className="dot"></span><b>Agent SEO</b><p>Recommandations classées par impact</p></div><button className="ghost">Tout analyser</button></div>{actions.map(a=><div className="action" key={a[1]}><span className={"badge "+a[3]}>{a[0]}</span><div><b>{a[1]}</b><p>{a[2]}</p></div><button className="arrow">→</button></div>)}</div><div className="panel"><div className="panelHead"><div><b>État des connexions</b><p>Sources de données</p></div></div><Connection name="WordPress" state={wp?.ok?"Connecté":"Connexion..." } ok={!!wp?.ok}/><Connection name="Search Console" state="À connecter"/><Connection name="Google Analytics 4" state="À connecter"/><Connection name="API SEO" state="À connecter"/><button className="full">Configurer les connexions</button></div></div><div className="panel roadmap"><div className="panelHead"><div><b>Vue d'ensemble</b><p>Le cockpit part volontairement de données réelles, jamais de chiffres simulés.</p></div></div><div className="empty"><div>⌁</div><h2>{wp?.ok?"WordPress est connecté":"Connexion WordPress en cours"}</h2><p>{wp?.ok?"Les contenus du site sont maintenant synchronisés. Ouvrez « Pages & Articles » pour les consulter.":"Les données apparaîtront dès que la connexion sera disponible."}</p></div></div></>}

function Content({wp}:{wp:WpData|null}){
 const [kind,setKind]=useState<"pages"|"posts">("pages");
 const items=kind==="pages"?(wp?.pages||[]):(wp?.posts||[]);
 return <><header><div><p className="eyebrow">CONTENU WORDPRESS</p><h1>Pages & Articles</h1><p className="sub">Contenus récupérés directement depuis rivieranuisibles.fr.</p></div><button onClick={()=>location.reload()}>↻ Actualiser</button></header>
 <div className="stats"><Card k="Connexion" v={wp?.ok?"Active":"—"} s={wp?.ok?"WordPress synchronisé":"Vérification..."}/><Card k="Pages chargées" v={wp?.ok?String(wp.pages?.length||0):"—"} s="Derniers contenus récupérés"/><Card k="Articles chargés" v={wp?.ok?String(wp.posts?.length||0):"—"} s="Derniers contenus récupérés"/><Card k="Compte" v={wp?.user?.name||"—"} s="Utilisateur WordPress"/></div>
 <div className="panel contentPanel"><div className="contentToolbar"><div><b>Contenus du site</b><p>Données réelles de l'API WordPress</p></div><div className="tabs"><button className={kind==="pages"?"tab activeTab":"tab"} onClick={()=>setKind("pages")}>Pages</button><button className={kind==="posts"?"tab activeTab":"tab"} onClick={()=>setKind("posts")}>Articles</button></div></div>
 {!wp?<div className="loading">Chargement de WordPress…</div>:!wp.ok?<div className="errorBox">Connexion WordPress impossible : {wp.error}</div>:<div className="contentTable"><div className="tableRow tableHead"><span>Titre</span><span>Statut</span><span>Dernière modification</span><span></span></div>{items.map(item=><div className="tableRow" key={item.id}><div><b dangerouslySetInnerHTML={{__html:item.title.rendered||item.title.raw||item.slug}}/><small>/{item.slug}</small></div><span className={"state "+item.status}>{item.status==="publish"?"Publié":item.status}</span><span>{new Date(item.modified).toLocaleDateString("fr-FR")}</span><a href={item.link} target="_blank" rel="noreferrer">Voir ↗</a></div>)}</div>}</div></>
}
function Card({k,v,s}:{k:string,v:string,s:string}){return <div className="card"><p>{k}</p><strong>{v}</strong><small>{s}</small></div>}
function Connection({name,state,ok=false}:{name:string,state:string,ok?:boolean}){return <div className="connection"><span className={"status "+(ok?"connected":"")}></span><b>{name}</b><small className={ok?"okText":""}>{state}</small></div>}
